# NumPy Tutorial 
## NumPy docs
https://docs.scipy.org/doc/numpy/index.html
## NumPy user guide
https://docs.scipy.org/doc/numpy/user/index.html
## NumPy reference¶
https://docs.scipy.org/doc/numpy/reference/index.html

# Import NumPy module

In [2]:
import numpy as np

In [3]:
print (np.__version__)

1.15.4


# Create NumPy array
## using list 

In [4]:
mylist = [-14, 12, 3, 2, 4, 5]
my_np_array = np.array(mylist)
my_np_array

array([-14,  12,   3,   2,   4,   5])

## using tuple 

In [5]:
my_tuple = (-6, 7, 19, 12, 14, 4)
my_np_array = np.array(my_tuple)
my_np_array

array([-6,  7, 19, 12, 14,  4])

## Difference between python and numpy data structures 

In [6]:
mylist*3

[-14, 12, 3, 2, 4, 5, -14, 12, 3, 2, 4, 5, -14, 12, 3, 2, 4, 5]

In [8]:
np.array(mylist)*3

array([-42,  36,   9,   6,  12,  15])

##  using NumPy's methods

In [9]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [11]:
np.arange(1, 8, 2)

array([1, 3, 5, 7])

In [12]:
np.linspace(5, 15, 9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((5,4), dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Array slicing

In [17]:
my_vector = np.array ([-14, 12, 3, 2, 4, 5])

In [18]:
my_vector[0]

-14

In [19]:
my_vector[-1]

5

In [20]:
my_vector[1:6:2]

array([12,  2,  5])

# Two dimensional array

In [21]:
my_array= np.arange(35)
my_array.shape = (7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [25]:
my_array[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
my_array[...,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27],
       [31, 32]])

In [27]:
row = 5
column = 2
my_array[row, column]

27

# Array mask

In [28]:
my_vector = np.array ([-14, 12, 3, 2, 4, 5])
zero_mod_2_mask = 0 == (my_vector % 2)
zero_mod_2_mask

array([ True,  True, False,  True,  True, False])

In [29]:
sub_array = my_vector[zero_mod_2_mask]
sub_array

array([-14,  12,   2,   4])

In [30]:
sub_array[sub_array>10]

array([12])

# Broadcasting

In [32]:
my_3D_array = np.arange(48)
my_3D_array.shape = (2,6,4)
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [33]:
# shape
my_3D_array.shape

(2, 6, 4)

In [34]:
# number of dimensions
my_3D_array.ndim

3

In [35]:
# size; number of elements
my_3D_array.size

48

In [36]:
# data type for each element
my_3D_array.dtype

dtype('int64')

In [37]:
3 * my_3D_array - 4

array([[[ -4,  -1,   2,   5],
        [  8,  11,  14,  17],
        [ 20,  23,  26,  29],
        [ 32,  35,  38,  41],
        [ 44,  47,  50,  53],
        [ 56,  59,  62,  65]],

       [[ 68,  71,  74,  77],
        [ 80,  83,  86,  89],
        [ 92,  95,  98, 101],
        [104, 107, 110, 113],
        [116, 119, 122, 125],
        [128, 131, 134, 137]]])

In [39]:
left_mat = np.arange(8).reshape((2,4))
right_mat = np.arange(20).reshape((4,5))

In [40]:
left_mat @ right_mat

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278]])

In [41]:
np.dot(left_mat, right_mat)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278]])

# Operations along axes

In [42]:
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [43]:
my_3D_array.shape

(2, 6, 4)

In [44]:
my_3D_array.sum()

1128

In [45]:
my_3D_array.sum(axis=0)

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46],
       [48, 50, 52, 54],
       [56, 58, 60, 62],
       [64, 66, 68, 70]])

In [46]:
my_3D_array.sum(axis=1)

array([[ 60,  66,  72,  78],
       [204, 210, 216, 222]])

In [47]:
my_3D_array.sum(axis=2)

array([[  6,  22,  38,  54,  70,  86],
       [102, 118, 134, 150, 166, 182]])

# Broadcasting rules

In [49]:
my_2D_array = np.ones(24, dtype='int_').reshape((6,4)) * 2
my_2D_array

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [52]:
my_random_2D_array = np.random.random((6,4))
my_random_2D_array

array([[0.6985, 0.8037, 0.7635, 0.4934],
       [0.8141, 0.7778, 0.9639, 0.5444],
       [0.6487, 0.1781, 0.855 , 0.871 ],
       [0.0845, 0.2303, 0.9988, 0.0176],
       [0.8937, 0.3848, 0.9796, 0.0314],
       [0.5941, 0.6453, 0.6142, 0.0543]])

In [55]:
# Broadcasting to last two dimensions
np.set_printoptions(precision=2)
my_3D_array * my_random_2D_array

array([[[ 0.  ,  0.8 ,  1.53,  1.48],
        [ 3.26,  3.89,  5.78,  3.81],
        [ 5.19,  1.6 ,  8.55,  9.58],
        [ 1.01,  2.99, 13.98,  0.26],
        [14.3 ,  6.54, 17.63,  0.6 ],
        [11.88, 13.55, 13.51,  1.25]],

       [[16.76, 20.09, 19.85, 13.32],
        [22.8 , 22.56, 28.92, 16.88],
        [20.76,  5.88, 29.07, 30.49],
        [ 3.04,  8.52, 37.95,  0.69],
        [35.75, 15.77, 41.14,  1.35],
        [26.14, 29.04, 28.25,  2.55]]])

In [53]:
my_vector = np.arange(4) * 2
my_vector[0] = -1
my_vector

array([-1,  2,  4,  6])

In [65]:

my_3D_array / my_vector

array([[[ -0.  ,   0.5 ,   0.5 ,   0.5 ],
        [ -4.  ,   2.5 ,   1.5 ,   1.17],
        [ -8.  ,   4.5 ,   2.5 ,   1.83],
        [-12.  ,   6.5 ,   3.5 ,   2.5 ],
        [-16.  ,   8.5 ,   4.5 ,   3.17],
        [-20.  ,  10.5 ,   5.5 ,   3.83]],

       [[-24.  ,  12.5 ,   6.5 ,   4.5 ],
        [-28.  ,  14.5 ,   7.5 ,   5.17],
        [-32.  ,  16.5 ,   8.5 ,   5.83],
        [-36.  ,  18.5 ,   9.5 ,   6.5 ],
        [-40.  ,  20.5 ,  10.5 ,   7.17],
        [-44.  ,  22.5 ,  11.5 ,   7.83]]])

# Views and copies

In [57]:
array1 = np.array([-34, -38, -30, -50, 1, 4, 7, 20])
array1

array([-34, -38, -30, -50,   1,   4,   7,  20])

In [58]:
# = as reference to same object 
array2 = array1
array2

array([-34, -38, -30, -50,   1,   4,   7,  20])

In [59]:
#reference equality
array1 is array2

True

In [60]:
# View as a shallow copy
array3 = array1.view()
array3.shape = (2, 4)
array3

array([[-34, -38, -30, -50],
       [  1,   4,   7,  20]])

In [61]:
array3 is array1

False

In [62]:
array1[3] = 1000
array3

array([[ -34,  -38,  -30, 1000],
       [   1,    4,    7,   20]])

In [63]:
# Deep Copy
array4 = array1.copy()
array4[3] = 999
array4

array([-34, -38, -30, 999,   1,   4,   7,  20])

In [64]:
array3

array([[ -34,  -38,  -30, 1000],
       [   1,    4,    7,   20]])


# Adding and removing elements
## append
https://docs.scipy.org/doc/numpy/reference/generated/numpy.append.html
## insert
https://docs.scipy.org/doc/numpy/reference/generated/numpy.insert.html
## delete
https://docs.scipy.org/doc/numpy/reference/generated/numpy.delete.html

# Joining and splitting arrays
## concatenate 
http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html
## stack 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html
## horizontal stacking
https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html
## vertical stacking
https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html
## split
https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html
# Other array manipulation routines
#https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html